
font_family      DejaVuSansM Nerd Font Mono
font_size 14.0

# this is the system window
hide_window_decorations yes
tab_bar_edge top
tab_bar_style slant

# these are splits in kitty
window_margin_width 4
window_padding_width 10
enabled layouts tall, *

shell nu
editor hx

notfy_on_cmd_finish unfocused

# Cursor Trail stuff
#cursor_trail 5
#cursor_trail_decay 0.01 0.5
#cursor_trail_start_threshold 2

# BEGIN_KITTY_THEME
# Argonaut
include current-theme.conf
# END_KITTY_THEME
