theme = "dracula_at_night"

[editor]
line-number = "relative"
bufferline = "always"
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

[keys.normal]
y = [":clipboard_yank", "yank"]

[keys.select]
y = [":clipboard_yank", "yank"]
