theme = "dracula_at_night"

[editor]
line-number = "relative"
bufferline = "always"
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.normal]
y = [":clipboard-yank", "yank"]

[keys.select]
y = [":clipboard-yank", "yank"]
